# Generated by Django 5.0.2 on 2024-02-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_alter_car_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colour',
        ),
    ]
